### ISSUE TITLE
Raspberry pi zero 2w

### ISSUE THREAD

**Issue by yzheka** [FYSETC/FYSETC-CTP40#10]
Is there any way to make it work on rpi zero 2w?

**Comment by Vossberger** [comment]
same question here, actually working on 64-Bit bullseye (Zero 2W). Display comes up at boot and turns of after 1 second. I used the Pi4 64-bit install script.

**Comment by yzheka** [comment]
ok, it works on 64-bit image but I am unable to rotate display. it also works on 32 bit image but there touch is not working

**Comment by ayufan** [comment]
To make this work you just need. It should work on any RPI board.

```
# /boot/config.txt
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dpi-hyperpixel4,rotate=270,touchscreen-swapped-x-y,touchscreen-inverted-x

# /etc/X11/xorg.conf.d/90-monitor.conf 
Section "Monitor"
    Identifier "DPI-1"
    Option "Rotate" "left"
EndSection
```

**Comment by yzheka** [comment]
> To make this work you just need. It should work on any RPI board.
> 
> ```
> # /boot/config.txt
> dtoverlay=vc4-kms-v3d
> dtoverlay=vc4-kms-dpi-hyperpixel4,rotate=270,touchscreen-swapped-x-y,touchscreen-inverted-x
> 
> # /etc/X11/xorg.conf.d/90-monitor.conf 
> Section "Monitor"
>     Identifier "DPI-1"
>     Option "Rotate" "left"
> EndSection
> ```

This is for clean raspberry os? No need to install any drivers from this repo?

**Comment by ayufan** [comment]
@yzheka Correct. Latest Raspbian OS. No need for any drivers.

**Comment by yzheka** [comment]
> @yzheka Correct. Latest Raspbian OS. No need for any drivers.

Wow, it works, thank y very much

**Comment by yzheka** [comment]
For me it was enough only to add
```
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dpi-hyperpixel4,rotate=90
``` 
into config.txt
All other parameters break touch orientation

**Comment by ayufan** [comment]
@yzheka It does depend what type of rotation you want. However, ultimately this is some combination of above.

The important thing is that everything is built-in.

**Comment by yzheka** [comment]
@ayufan right. But for me it seemed to work ok without touch related parameters. Touch orientation follow screen rotation. Maybe it depends on display revision, I don't know. But any way thank you very much for such simple solution, you saved me much time on digging and solving that
